name: Deploy Documentation to GitHub Pages

on:
  release:
    types: [created]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build Documentation
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Setup node enviroment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Build documentation
        run: npm run typedoc:build
      - name: Setup pages
        uses: actions/configure-pages@v3
        id: pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./docs
  deploy:
    name: Deploy to GitHub Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: self-hosted
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        id: deployment