
name: Check on commit

on:
  push:
    branches:
      - "master"
      - "develop"
      - "feature_*"
      - "fix_*"
  workflow_dispatch:

jobs:
  tests:
    name: Test
    runs-on: self-hosted

    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x, 14.x, 16.x, 18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Clean installation of project
        run: npm ci
      - name: Run unit tests
        run: npm run tests:all

  lint:
    name: Lint
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Clean install
        run: npm ci
      - name: Lint
        run: npm run lint
