name: Node.js CI

on:
  release:
    types: [created]

jobs:
  tests:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node enviroment
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Clean installation of project
        run: npm ci
      - name: Run unit tests
        run: npm run tests:all

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Clean install
        run: npm ci
      - name: Lint
        run: npm run lint

  format:
    name: Format Code
    runs-on: ubuntu-latest
    needs: [tests, lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          commit_message: "style: format code"
          prettier_options: "--write ./src"

  build:
    name: Build
    needs: [tests, lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node enviroment
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Clean installation
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: BuildArtifact
          if-no-files-found: error
          path: |
            ./out
            ./package.json
            ./tsconfig.json
            ./README.md
            ./LICENSE

  publish-npm:
    name: Publish
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node enviroment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: BuildArtifact
      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
