name: Node.js CI

on:
  release:
    types: [created]

jobs:
  tests:
    name: Test
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x, 18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Uses Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Clean installation of project
        run: npm ci
      - name: Run unit tests
        run: npm run tests:all

  lint:
    name: Lint
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Clean install
        run: npm ci
      - name: Lint
        run: npm run lint

  build:
    name: Build
    needs: [tests, lint]
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node enviroment
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Clean installation
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: BuildArtifact
          if-no-files-found: error
          path: |
            ./out
            ./package.json
            ./tsconfig.json
            ./README.md
            ./LICENSE

  publish-npm:
    name: Publish
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node enviroment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: BuildArtifact
      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
